version: "3.7"

services:
  postgres_database:
    container_name: "pockafka"
    image: "postgres:12-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pockafka
      - POSTGRES_PASSWORD=pockafka
      - POSTGRES_DB=pockafka

#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.7
#    ports:
#      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: docker.io/bitnami/kafka:3
#    ports:
#      - "9092:9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local