server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pockafka
    username: pockafka
    password: pockafka
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL93Dialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL93Dialect
    show-sql: true
    properties:
      javax:
        persistence:
          query:
            timeout: 60000
