server:
  port: 8080
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: car-position
    consumer:
      bootstrap-servers: localhost:29092
      client-id: consumer
      group-id: position
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/pockafka
    username: pockafka
    password: pockafka
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL93Dialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL93Dialect
    show-sql: true
    properties:
      javax:
        persistence:
          query:
            timeout: 60000
topic:
  name:
    producer: car-position
uto:
  create:
    topics:
      enable: true